INSERT INTO USERS VALUES ('DAVID', '$2a$10$vsMf.RQM/cg3nUjoYU8WH.bB9abGYVeE/rmSPLZ3UAR6/WksudUUu', 'ADMIN', 1);
INSERT INTO USERS VALUES ('USER', '$2a$10$vsMf.RQM/cg3nUjoYU8WH.bB9abGYVeE/rmSPLZ3UAR6/WksudUUu', 'USER', 1);

COMMIT;