CREATE TABLE IF NOT EXISTS USER (
    ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(4000),
    ROLE VARCHAR(20),
    ENABLED SMALLINT NOT NULL DEFAULT 1,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    IS_COMPANY BOOLEAN,
    COMPANY_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CREDIT_CARD (
    NBR BIGINT,
    BALANCE DECIMAL(12,2),
    CARD_LIMIT DECIMAL(12,2),
    MONTH_EXP INT,
    YEAR_EXP INT,
    CVV VARCHAR(3),
    OWNER_ID INT,
    PRIMARY KEY (NBR),
    FOREIGN KEY (OWNER_ID) REFERENCES USER(ID)
);

CREATE TABLE IF NOT EXISTS CREDIT_CARD_TRANSACTION (
    ID INT AUTO_INCREMENT,
    AMOUNT DECIMAL(12,2),
    DESCRIPTION VARCHAR(500),
    TIMESTAMP TIMESTAMP,
    CREDIT_CARD_NBR BIGINT,
    IS_PREAUTH BOOLEAN,
    PRIMARY KEY (ID),
    FOREIGN KEY (CREDIT_CARD_NBR) REFERENCES CREDIT_CARD(NBR)
);

CREATE TABLE IF NOT EXISTS DEBIT_CARD (
    NBR BIGINT,
    BALANCE DECIMAL(12,2),
    OWNER_ID INT,
    PRIMARY KEY(NBR),
    FOREIGN KEY(OWNER_ID) REFERENCES USER(ID)
);

CREATE TABLE IF NOT EXISTS DEBIT_CARD_TRANSACTION (
    ID INT AUTO_INCREMENT,
    AMOUNT DECIMAL(12,2),
    DESCRIPTION VARCHAR(500),
    TIMESTAMP TIMESTAMP,
    DEBIT_CARD_NBR BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEBIT_CARD_NBR) REFERENCES DEBIT_CARD(NBR)
);

CREATE TABLE IF NOT EXISTS PAYMENT_BROKER (
    ID INT AUTO_INCREMENT,
    API_KEY VARCHAR(11),
    SECRET VARCHAR(16),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CHALLENGE (
	ID INT AUTO_INCREMENT,
	QUESTION VARCHAR(100),
	RESPONSE VARCHAR(500),
	USERNAME VARCHAR(100),
	PRIMARY KEY (ID),
	FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME)
);

CREATE TABLE IF NOT EXISTS USER_CHALLENGE_TOKEN (
	ID INT AUTO_INCREMENT,
	USERNAME VARCHAR(100),
	CHALLENGE_ID INT,
	TOKEN VARCHAR(1000),
	TIMESTAMP TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (CHALLENGE_ID) REFERENCES CHALLENGE(ID),
	FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME)
);


