
CREATE TABLE IF NOT EXISTS USERS (
	ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(4000),
    ROLE VARCHAR(20),
    ENABLED SMALLINT NOT NULL DEFAULT 1,
    PRIMARY KEY (ID)
);

