CREATE TABLE IF NOT EXISTS USER (
    ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(4000),
    ROLE VARCHAR(20),
    ENABLED SMALLINT NOT NULL DEFAULT 1,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CREDIT_CARD (
    NBR BIGINT,
    BALANCE DECIMAL(12,2),
    CARD_LIMIT DECIMAL(12,2),
    MONTH_EXP INT,
    YEAR_EXP INT,
    CVV INT,
    OWNER_ID INT,
    PRIMARY KEY (NBR),
    FOREIGN KEY (OWNER_ID) REFERENCES USER(ID)
);

CREATE TABLE IF NOT EXISTS CREDIT_CARD_TRANSACTION (
    ID INT AUTO_INCREMENT,
    AMOUNT DECIMAL(12,2),
    DESCRIPTION VARCHAR(500),
    TIMESTAMP TIMESTAMP,
    CREDIT_CARD_NBR BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (CREDIT_CARD_NBR) REFERENCES CREDIT_CARD(NBR)
);

CREATE TABLE IF NOT EXISTS DEBIT_CARD (
    NBR BIGINT,
    BALANCE DECIMAL(12,2),
    OWNER_ID INT,
    PRIMARY KEY(NBR),
    FOREIGN KEY(OWNER_ID) REFERENCES USER(ID)
);

CREATE TABLE IF NOT EXISTS DEBIT_CARD_TRANSACTION (
    ID INT AUTO_INCREMENT,
    AMOUNT DECIMAL(12,2),
    DESCRIPTION VARCHAR(500),
    TIMESTAMP TIMESTAMP,
    DEBIT_CARD_NBR BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEBIT_CARD_NBR) REFERENCES DEBIT_CARD(NBR)
);

CREATE TABLE IF NOT EXISTS PAYMENT_BROKER (
    ID INT AUTO_INCREMENT,
    API_KEY VARCHAR(11),
    SECRET VARCHAR(16),
    PRIMARY KEY (ID)
);


